sudo: required

image: alpine
services:
  - docker

install:
  - docker build . -t laravel-ci:local

after_install:
  - docker images

script:
  - git clone https://github.com/laravel/laravel.git test
  - docker build . -f Dockerfile-ci

after_success:
  - rm -rf ./test
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch
  - git checkout master 
  - git merge origin/develop --no-ff --no-edit

  - openssl aes-256-cbc -K $encrypted_f3aea5cacb96_key -iv $encrypted_f3aea5cacb96_iv
    -in id_rsa.enc -out id_rsa -d
  - mv id_rsa ~/.ssh/id_rsa
  - sudo chmod 600 ~/.ssh/id_rsa

  - git remote add upstream git@github.com:GuessEver/docker-laravel-ci.git
  - git fetch upstream

  - git config user.name "Travis CI"
  - git push upstream master
